version: "3.3"
services:

  v-bank-app:
    image: vargadan/v-bank-app:latest
    ports:
      - "80:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://v-bank-db:3306/vbankdb
      - spring.datasource.username=root
      - spring.datasource.password=H3ll0Bel4
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - enableCSRFProtection=true
    networks:
      - v-bank-net

  v-bank-db:
    image: fedora/mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=vbankuser
      - MYSQL_PASSWORD=vbank_p4ss
      - MYSQL_DATABASE=vbankdb
      - MYSQL_ROOT_PASSWORD=H3ll0Bel4
    networks:
      - v-bank-net

networks:
  v-bank-net: